### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(HarmonyContent)
add_subdirectory(Harmony)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    HarmonyContentplugin
    Harmonyplugin)